config/routes.rb
Rails.application.routes.draw do


  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }
  # ゲストログイン用
  devise_scope :customer do
   post 'customers/guest_sign_in'=>'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to:'homes#top'
    get 'about'=>'homes#about',as:'about'
    resources:customers,only:[:index,:show,:edit,:update] do
      collection do
        get 'confilm'
        patch 'withdrawal'
      end
    end
    resources:post_shogi_places do
      resources:postcomments,only:[:create,:destroy]
      resource:favorites,only:[:create,:destroy]
    end
    get 'search_tag'=>'post_shogi_places#search_tag'
    get 'search_keyword'=>'post_shogi_places#search_keyword'
    get 'multi_criteria_search'=>'post_shogi_places#multi_criteria_search'
  end

  get 'admin'=>'admin/homes#top',as:'admin'

  namespace :admin do
    resources:customers,only:[:index,:show,:edit,:update]
    resources:post_shogi_places,only:[:show,:destroy] do
      resources:postcomments,only:[:destroy]
    end
    get 'search_tag'=>'post_shogi_places#search_tag'
    get 'search_keyword'=>'post_shogi_places#search_keyword'
    get 'multi_criteria_search'=>'post_shogi_places#multi_criteria_search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:post_shogi_places,dependent: :destroy
  has_many:postcomments,     dependent: :destroy
  has_many:favorites,        dependent: :destroy

  has_one_attached:customer_image

  enum gender:{male:0,woman:1}
  enum membership_status:{member:0,withdrawal:1,stop:2}

  validates:name,length: {minimum: 1,maximum: 15},uniqueness: true
  validates:email,presence:true
  validates:date_of_birth,presence:true
  validates:gender,presence:true
  validates:chess_ability,presence:true
  validates:profile,length: {maximum: 100}

  # ゲストログイン用のニックネーム、パスワード等の設定の記述
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー') do |customer|
      customer.password=SecureRandom.urlsafe_base64
      customer.email='aaa@aaa.com'
      customer.date_of_birth='2000-01-01'
      customer.gender='male'
      customer.chess_ability='初心者'
    end
  end


  def get_customer_image(width,height)
    unless customer_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      customer_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    customer_image.variant(resize_to_limit:[width,height]).processed
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action:authenticate_admin!
  def index
    @customers=Customer.page(params[:page])
  end

  def show
    @customer=Customer.find(params[:id])
    @post_shogi_places=@customer.post_shogi_places.page(params[:page])
    @postcomments=@customer.postcomments.page(params[:page])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    if @customer.update(customer_params)
       flash[:notice]="会員情報を更新しました。"
       redirect_to admin_customer_path(@customer.id)
    else
       render:edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name,:email,:date_of_birth,:gender,:chess_ability,:profile,:membership_status)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">会員情報編集</h2>

  <div class="m-5"><% if @customer.errors.any? %>
    <h5><%= @customer.errors.count %>件のエラーが発生しました。</h5>
      <% @customer.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
      </ul>
      <% end %>
    <% end %>
  </div>

    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <p>会員id</p>
      </div>
      <div class="col-md-5 col-10">
        <%= @customer.id %>
      </div>
    </div>

  <%= form_with model:@customer,url:admin_customer_path(@customer.id),method: :patch do |f| %>
    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <label for="name">ニックネーム</label>
      </div>
      <div class="col-md-5 col-10">
        <%= f.text_field:name,id:"name",class:"w-100" %>
      </div>
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <label for="email">メールアドレス</label>
      </div>
      <div class="col-md-5 col-10">
        <%= f.email_field:email,id:"email",class:"w-100" %>
      </div>
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <p>生年月日</p>
      </div>
      <div class="col-md-5 col-10">
        <%= f.date_select :date_of_birth,use_month_numbers: true,start_year: 1920,end_year: (Time.now.year),selected:@customer.date_of_birth %>
      </div>
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <p>性別</p>
      </div>
      <div class="col-md-5 col-10">
        <%= f.radio_button:gender,"male" %>
        <%= f.label:gender,"男性",{style: "display: inline-block;"} %>
        <%= f.radio_button:gender,"woman",class:"ml-3" %>
        <%= f.label:gender,"女性",{style: "display: inline-block;"} %>
      </div>
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <label for="ability">棋力</label>
      </div>
      <div class="col-md-5 col-10">
        <%= f.text_field:chess_ability,id:"ability",class:"w-100" %>
      </div>
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <label for="profile">プロフィール</label>
      </div>
      <div class="col-md-5 col-10">
        <%= f.text_area:profile,id:"profile",class:"w-100",rows:3 %>
      </div>
    </div>

    <div class="row justify-content-center mb-4">
      <div class="col-md-5 col-10">
        <p>会員ステータス</p>
      </div>
      <div class="col-md-5 col-10">
        <%= f.radio_button:membership_status,"member" %>
        <%= f.label:membership_status,"有効",{style: "display: inline-block;"} %>
        <%= f.radio_button:membership_status,"withdrawal",class:"ml-3" %>
        <%= f.label:membership_status,"退会",{style: "display: inline-block;"} %>
        <%= f.radio_button:membership_status,"stop",class:"ml-3" %>
        <%= f.label:membership_status,"停止",{style: "display: inline-block;"} %>
      </div>
    </div>

    <div class="row justify-content-center">
      <%= f.submit"更新する",class:"btn btn-success col-4aac" %>
    </div>

  <% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">会員一覧</h2>

  <table class="table table-striped text-break">
    <thead>
      <tr>
        <th style="width: 35%">プロフィール画像</th>
        <th style="width: 25%">ニックネーム</th>
        <th style="width: 25%">メールアドレス</th>
        <th style="width: 15%">ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= image_tag customer.get_customer_image(80,80) %></td>
          <td class="align-middle"><%= link_to customer.name,admin_customer_path(customer.id) %></td>
          <td class="align-middle"><%= customer.email %></td>

          <% if customer.membership_status=="member" %>
            <td class="align-middle text-success"><%= Customer.membership_statuses_i18n[:"#{customer.membership_status}"] %></td>
          <% elsif customer.membership_status=="withdrawal" %>
            <td class="align-middle text-secondary"><%= Customer.membership_statuses_i18n[:"#{customer.membership_status}"] %></td>
          <% else %>
            <td class="align-middle text-danger"><%= Customer.membership_statuses_i18n[:"#{customer.membership_status}"] %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @customers %>

</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">会員詳細</h2>

  <div class="row">
    <div class="col-md-4 col-12 mb-5">
      <div class="text-center border p-3">
        <%= image_tag @customer.get_customer_image(80,80),class:"m-3" %><br>
        <p class="mb-3"><%= @customer.name %></p>
        <p class="mb-3"><%= @customer.email %></p>
        <p class="mb-3"><%= @customer.date_of_birth.strftime('%Y年%m月%d日')+"生" %></p>
        <p>性別：<%= Customer.genders_i18n[:"#{@customer.gender}"] %></p>
        <p>棋力：<%= @customer.chess_ability %></p>
        <p class="p-2"><%= @customer.profile %></p>

        <% if @customer.membership_status=="member" %>
            <p>会員ステータス：<span class="text-success"><%= Customer.membership_statuses_i18n[:"#{@customer.membership_status}"] %></span></p>
          <% elsif @customer.membership_status=="withdrawal" %>
            <p>会員ステータス：<span class="text-secondary"><%= Customer.membership_statuses_i18n[:"#{@customer.membership_status}"] %></span></p>
          <% else %>
            <p>会員ステータス：<span class="text-danger"><%= Customer.membership_statuses_i18n[:"#{@customer.membership_status}"] %></span></p>
          <% end %>

        <%= link_to "編集する",edit_admin_customer_path(@customer.id),class:"btn btn-success" %>
      </div>
    </div>

    <div class="offset-md-1 col-md-7 col-12">
      <p class="text-center mb-3">投稿履歴一覧</p>

      <table class="table border-bottom">
        <thead>
          <tr>
            <th style="width:35%;">画像</th>
            <th style="width:30%;">対局場所名</th>
            <th style="width:35%;">説明</th>
          </tr>
        </thead>

        <tbody>
          <% @post_shogi_places.each do |post_shogi_place| %>
          <tr>
            <td><%= image_tag post_shogi_place.get_shogi_place_image(80,80) %></td>
            <td><%= link_to post_shogi_place.name,admin_post_shogi_place_path(post_shogi_place.id) %></td>
            <td><p class="explanation"><%= post_shogi_place.explanation %></p></td>
          <% end %>
          </tr>
        </tbody>
      </table>

      <%= paginate @post_shogi_places %>

      <p class="text-center mt-5 mb-3">コメント履歴一覧</p>
      <table class="table">
        <thead>
          <tr>
            <th style="width:30%;">対局場所名</th>
            <th style="width:45%;">コメント内容</th>
            <th style="width:25%;"></th>
          </tr>
        </thead>

        <tbody>
          <% @postcomments.each do |postcomment| %>
          <tr>
            <td><%= postcomment.post_shogi_place.name %></td>
            <td><%= postcomment.comment %></td>
            <td><%= link_to "削除",admin_post_shogi_place_postcomment_path(postcomment.post_shogi_place,postcomment),method: :delete,"data-confirm"=>"本当に削除しますか？",class:"btn btn-danger" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @postcomments %>
    </div>
  </div>
</div>