config/routes.rb
Rails.application.routes.draw do


  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }
  # ゲストログイン用
  devise_scope :customer do
   post 'customers/guest_sign_in'=>'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to:'homes#top'
    get 'about'=>'homes#about',as:'about'
    resources:customers,only:[:index,:show,:edit,:update] do
      collection do
        get 'confilm'
        patch 'withdrawal'
      end
    end
    resources:post_shogi_places do
      resources:postcomments,only:[:create,:destroy]
      resource:favorites,only:[:create,:destroy]
    end
    get 'search_tag'=>'post_shogi_places#search_tag'
    get 'search_keyword'=>'post_shogi_places#search_keyword'
    get 'multi_criteria_search'=>'post_shogi_places#multi_criteria_search'
  end

  get 'admin'=>'admin/homes#top',as:'admin'

  namespace :admin do
    resources:customers,only:[:index,:show,:edit,:update]
    resources:post_shogi_places,only:[:show,:destroy] do
      resources:postcomments,only:[:destroy]
    end
    get 'search_tag'=>'post_shogi_places#search_tag'
    get 'search_keyword'=>'post_shogi_places#search_keyword'
    get 'multi_criteria_search'=>'post_shogi_places#multi_criteria_search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_shogi_place.rb
class PostShogiPlace < ApplicationRecord
  has_many:favorites,               dependent: :destroy
  has_many:postcomments,            dependent: :destroy
  has_many:target_audiences_tag_relations, dependent: :destroy
  has_many:target_audiences,        through: :target_audiences_tag_relations
  has_many:taggings,                dependent: :destroy
  has_many:tags,                    through: :taggings
  belongs_to:customer
  belongs_to:prefecture
  attr_accessor :tag_name
  # 住所登録時と変更時にgeocoderが緯度・経度のデータを登録・更新するのに必要
  geocoded_by :address
  after_validation :geocode

  has_one_attached:shogi_place_image

  validates:prefecture_id,presence:true
  validates:name,presence:true
  validates:address,presence:true
  validates:telephone_number,presence:true
  validates:explanation,length: {minimum: 1,maximum: 255}

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags=self.tags.pluck(:name)
    unless self.tags.nil?
  # 現在取得したタグから送られてきたタグを除いてoldtagとする
      old_tags = current_tags - sent_tags
  # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
      new_tags = sent_tags - current_tags

    #古いタグを消す
      old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
      end

    # 新しいタグを保存
      new_tags.each do |new|
      new_tagging=Tag.find_or_create_by(name: new)
        self.tags << new_tagging
      end
    end
  end

  # キーワード検索方法分岐
  def self.looks(range,word)
    if range=="対局場所名"
       @post_shogi_place=PostShogiPlace.where("name LIKE?","%#{word}%")
    else
       @post_shogi_place=PostShogiPlace.where("address LIKE?","%#{word}%")
    end
  end

  # いいねをクリックしたcustomerのidがfavoritesテーブルに存在するかどうかを調べる
  def favorited_by?(customer)
    favorites.exists?(customer_id:customer.id)
  end

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}

  def get_shogi_place_image(width,height)
    unless shogi_place_image.attached?
      file_path=Rails.root.join('app/assets/images/no_image.jpg')
      shogi_place_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    shogi_place_image.variant(resize_to_limit:[width,height]).processed
  end
end

app/controllers/admin/post_shogi_places_controller.rb
class Admin::PostShogiPlacesController < ApplicationController
  before_action:authenticate_admin!
  def show
    @post_shogi_place=PostShogiPlace.find(params[:id])
    @tags=@post_shogi_place.tags
    @target_audiences=@post_shogi_place.target_audiences
    @postcomments=@post_shogi_place.postcomments.page(params[:page])
  end

  def destroy
    post_shogi_place=PostShogiPlace.find(params[:id])
    post_shogi_place.destroy
    redirect_to admin_path
  end

  def search_tag
    @tags=Tag.all
    @tag=Tag.find(params[:tag_id])
    @post_shogi_places=@tag.post_shogi_place.page(params[:page])
  end

  def search_keyword
    @post_shogi_places=PostShogiPlace.looks(params[:range],params[:word]).page(params[:page])
  end

  def multi_criteria_search
    @prefecture=Prefecture.find(params[:prefecture_id])
    @target_audience=TargetAudience.find(params[:target_audience_id])
    @post_shogi_places=PostShogiPlace.joins(:target_audiences).where("post_shogi_places.prefecture_id LIKE ? AND target_audiences.id LIKE ?","#{params[:prefecture_id]}","#{params[:target_audience_id]}").page(params[:page])
  end
end

app/views/admin/post_shogi_places/_list.html.erb
<% post_shogi_places.each do |post_shogi_place| %>
  <div class="row border mb-3 p-3">
    <div class="text-center col-md-4 col-12">
      <%= image_tag post_shogi_place.get_shogi_place_image(180,180) %><br>
      <p class="mt-3 mb-3">投稿日：<%= post_shogi_place.created_at.strftime('%Y/%m/%d') %></p>
    </div>
    <div class="col-md-8 col-12">
      <div class="mb-3">
        <%= image_tag post_shogi_place.customer.get_customer_image(80,80) %>
        <%= link_to post_shogi_place.customer.name,admin_customer_path(post_shogi_place.customer.id),class:"ml-5" %>
      </div>
      <p><%= link_to post_shogi_place.name,admin_post_shogi_place_path(post_shogi_place.id) %></p>
      <p>住所：<%= post_shogi_place.address %></p>
      <p class="explanation">説明：<%= post_shogi_place.explanation %></p>
    </div>
  </div>
<% end %>

app/views/admin/post_shogi_places/multi_criteria_search.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">"<%= @prefecture.name %>"の"<%= @target_audience.name %>"の投稿一覧</h2>

  <%= render 'list',post_shogi_places:@post_shogi_places %>
  <%= paginate @post_shogi_places %>

  <div class="row justify-content-center mt-5">
    <%= link_to "投稿一覧へ戻る",admin_path,class:"btn btn-primary" %>
  </div>
</div>

app/views/admin/post_shogi_places/search_keyword.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">"<%= params[:word] %>"の検索結果一覧</h2>

  <%= render 'list',post_shogi_places:@post_shogi_places %>
  <%= paginate @post_shogi_places %>

  <div class="row justify-content-center mt-5">
    <%= link_to "投稿一覧へ戻る",admin_path,class:"btn btn-primary" %>
  </div>
</div>

app/views/admin/post_shogi_places/search_tag.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">タグが"<%= @tag.name %>"の投稿一覧</h2>

  <%= render 'list',post_shogi_places:@post_shogi_places %>
  <%= paginate @post_shogi_places %>

  <p class="mt-5">タグ一覧</p>
  <!--タグリスト-->
  <% @tags.each do |tag| %>
    <% unless tag.post_shogi_place.count==0 %>
      <%= link_to tag.name,admin_search_tag_path(tag_id: tag.id) %>
      <%= "(#{tag.post_shogi_place.count})" %>
    <% end %>
  <% end %>

  <div class="row justify-content-center mt-5">
    <%= link_to "投稿一覧へ戻る",admin_path,class:"btn btn-primary" %>
  </div>

</div>

app/views/admin/post_shogi_places/show.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">投稿詳細</h2>

  <div class="row border-bottom pb-5">
    <div class="text-center col-md-4 col-12 p-2 mb-5">
      <!-- Googleマップ表示エリア(地図を表示) -->
      <div style="width:100%; height:300px;" id="map"></div>

      <!-- Googleマップ表示用の Javascript -->
      <script>
        function initMap(){
        // 地図の位置情報(緯度・経度)を取得
        let mapPosition = {lat: <%= @post_shogi_place.latitude || 0 %> , lng: <%= @post_shogi_place.longitude || 0 %> };
        let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: mapPosition
        });
        let transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        let contentString = '【住所】<%= @post_shogi_place.address %>';
        let infowindow = new google.maps.InfoWindow({
          content: contentString
        });

        let marker = new google.maps.Marker({
          position: mapPosition,
          map: map,
          title: contentString
        });

        marker.addListener('click', function(){
          infowindow.open(map, marker);
        });
      }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

    </div>

    <div class="offset-1 col-md-7 col-12">
      <%= image_tag @post_shogi_place.get_shogi_place_image(230,230) %><br>
      <h4 class="mt-5"><%= @post_shogi_place.name %></h4>
      <p class="mt-5 mb-3"><%= @post_shogi_place.address %></p>
      <p class="mt-3"><%= @post_shogi_place.telephone_number %></p>
      <p>タグ：
      <!--タグリスト-->
      <% @tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
      </p>
      <% @target_audiences.each do |target_audience| %>
        <%= target_audience.name %><br>
      <% end %>
      <p class="mt-3"><%= @post_shogi_place.explanation %></p>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="offset-sm-2 col-sm-2 col-12 mb-3">
      <%= image_tag @post_shogi_place.customer.get_customer_image(80,80) %>
    </div>
    <div class="offset-sm-1 col-sm-6 col-12">
      <%= link_to @post_shogi_place.customer.name,admin_customer_path(@post_shogi_place.customer.id) %>
      <p class="mt-3">投稿日：<%= @post_shogi_place.created_at.strftime('%Y年%m月%d日') %></p>
      <div class="row mt-3">
        <i class="far fa-comment-dots ml-3 mr-2"></i>
          <%= @post_shogi_place.postcomments.count %>
          <p class="ml-md-5 ml-3">
          ❤ <%= @post_shogi_place.favorites.count %> いいね
        </p>
      </div>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <%= link_to "投稿削除",admin_post_shogi_place_path(@post_shogi_place.id),method: :delete,"data-confirm"=>"本当に削除しますか？",class:"btn btn-danger col-md-4 col-5 mb-2" %>
  </div>

  <div class="border-top mt-5">
    <p class="m-5">コメント一覧</p>
    <div class="mb-2">
      <p><%= @post_shogi_place.postcomments.count %>件コメント</p>
    </div>

    <% @postcomments.each do |postcomment| %>
      <div class="row border mb-2">
        <div class="d-flex align-items-center col-md-2 col-5 mt-2">
          <%= image_tag postcomment.customer.get_customer_image(80,80) %>
        </div>
        <div class="d-flex align-items-center col-md-3 col-5 mt-2">
          <%= link_to postcomment.customer.name,admin_customer_path(postcomment.customer.id) %>
        </div>
        <div class="d-flex align-items-center col-md-5 col-12 mt-2 mb-2">
          <%= postcomment.comment %>
        </div>
        <div class="d-flex align-items-center col-md-2 col-12 mt-2 mb-2">
          <%= link_to "削除",admin_post_shogi_place_postcomment_path(postcomment.post_shogi_place,postcomment),method: :delete,"data-confirm"=>"本当に削除しますか？",class:"btn btn-danger" %>
        </div>
      </div>
    <% end %>

    <%= paginate @postcomments %>

  </div>
</div>